import { PaymentMethod } from '../src/generated/prisma'

export const reportCategoriesData = [
	{ name: 'Blood Tests', description: 'Routine and advanced blood investigations' },
	{ name: 'Imaging', description: 'X-ray, MRI, CT, Ultrasound' },
	{ name: 'Pathology', description: 'Tissue and cytology reports' },
	{ name: 'Microbiology', description: 'Culture and sensitivity, infection screening' },
	{ name: 'Cardiology', description: 'ECG, Echo, TMT, Holter' },
]

export const categoriesData = [
	{ name: 'Antibiotics', description: 'Drugs to treat bacterial infections' },
	{ name: 'Pain Relief', description: 'Analgesics and pain management' },
	{ name: 'Antipyretics', description: 'Fever reducing medicines' },
	{ name: 'Vitamins & Supplements', description: 'Nutritional supplements' },
	{ name: 'Antacids', description: 'For acidity and heartburn' },
	{ name: 'Couch & Cold', description: 'Cough syrups and cold remedies' },
	{ name: 'Antidiabetics', description: 'Diabetes management drugs' },
	{ name: 'Antihistamines', description: 'Allergy medications' },
	{ name: 'Cardiac Care', description: 'Heart and blood pressure medicines' },
	{ name: 'Dermatology', description: 'Skin care medicines' },
	{ name: 'Medical Devices', description: 'Diagnostic and therapeutic devices' },
	{ name: 'First Aid', description: 'Supplies for minor injuries and emergencies' },
	{ name: 'Personal Care', description: 'Hygiene and grooming products' },
	{ name: "Women's Health", description: 'Products for feminine hygiene and reproductive health' },
	{ name: "Men's Health", description: 'Products for male-specific health needs' },
	{ name: 'Pediatric Care', description: 'Products for infants and children' },
	{ name: 'Mental Health', description: 'Medications for mental health conditions' },
]

export const suppliersData = [
	{ name: 'Cipla Ltd', contactPerson: 'Rajesh Kumar', email: 'contact@cipla.com', phone: '9876543210', address: 'Mumbai, India' },
	{ name: 'Sun Pharma', contactPerson: 'Anita Sharma', email: 'info@sunpharma.com', phone: '9123456789', address: 'Goregaon, Mumbai' },
	{ name: "Dr. Reddy's", contactPerson: 'Suresh Reddy', email: 'sales@drreddys.com', phone: '9988776655', address: 'Hyderabad, India' },
	{ name: 'Abbott Healthcare', contactPerson: 'Priya Singh', email: 'abbott@health.com', phone: '9001122334', address: 'Bandra, Mumbai' },
	{ name: 'Pfizer India', contactPerson: 'John Mathew', email: 'pfizer@india.com', phone: '9112233445', address: 'Delhi, India' },
]

export const itemsData = [
	{
		name: 'Ibuprofen',
		manufacturer: 'PharmaCorp',
		generic_name: 'Ibuprofen',
		formulation: 'Tablet',
		strength: '200mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Great for aches, pains, and fevers!',
		units_per_pack: 100,
		price: 5.99,
		purchase_price: 4.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1500,
		expiry_date: new Date('2026-10-15'),
		purchase_date: new Date('2024-05-20'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Pain Relief', 'Antipyretics'],
	},
	{
		name: 'Amoxicillin',
		manufacturer: 'Global Meds',
		generic_name: 'Amoxicillin',
		formulation: 'Capsule',
		strength: '500mg',
		unit: 'capsule',
		schedule: 'Rx',
		description: 'A common antibiotic to fight off bugs!',
		units_per_pack: 30,
		price: 12.5,
		purchase_price: 9.25,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 800,
		expiry_date: new Date('2025-12-01'),
		purchase_date: new Date('2024-04-10'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Antibiotics'],
	},
	{
		name: 'Paracetamol',
		manufacturer: 'HealthSolutions',
		generic_name: 'Acetaminophen',
		formulation: 'Tablet',
		strength: '500mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Your go-to for pain and fever relief!',
		units_per_pack: 200,
		price: 3.25,
		purchase_price: 2.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 300,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 2000,
		expiry_date: new Date('2027-03-20'),
		purchase_date: new Date('2024-06-01'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Pain Relief', 'Antipyretics'],
	},
	{
		name: 'Omeprazole',
		manufacturer: 'GastroCare',
		generic_name: 'Omeprazole',
		formulation: 'Capsule',
		strength: '20mg',
		unit: 'capsule',
		schedule: 'OTC',
		description: 'Helps calm that burning stomach acid!',
		units_per_pack: 42,
		price: 18.75,
		purchase_price: 15.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 600,
		expiry_date: new Date('2026-08-10'),
		purchase_date: new Date('2024-03-15'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Antacids'],
	},
	{
		name: 'Cetirizine',
		manufacturer: 'AllergyRelief',
		generic_name: 'Cetirizine HCl',
		formulation: 'Tablet',
		strength: '10mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Say goodbye to allergies, without the sleepiness!',
		units_per_pack: 30,
		price: 7.1,
		purchase_price: 5.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1200,
		expiry_date: new Date('2025-11-25'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['Antihistamines'],
	},
	{
		name: 'Lisinopril',
		manufacturer: 'CardioPharma',
		generic_name: 'Lisinopril',
		formulation: 'Tablet',
		strength: '10mg',
		unit: 'tablet',
		schedule: 'Rx',
		description: 'Helps keep your blood pressure in check!',
		units_per_pack: 90,
		price: 22.0,
		purchase_price: 18.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 40,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 450,
		expiry_date: new Date('2026-06-30'),
		purchase_date: new Date('2024-02-20'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Cardiac Care'],
	},
	{
		name: 'Atorvastatin',
		manufacturer: 'LipidHealth',
		generic_name: 'Atorvastatin calcium',
		formulation: 'Tablet',
		strength: '20mg',
		unit: 'tablet',
		schedule: 'Rx',
		description: 'Works to lower your cholesterol levels!',
		units_per_pack: 90,
		price: 35.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 30,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 300,
		expiry_date: new Date('2027-01-18'),
		purchase_date: new Date('2024-01-05'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Cardiac Care'],
	},
	{
		name: 'Metformin',
		manufacturer: 'DiabetiCare',
		generic_name: 'Metformin HCl',
		formulation: 'Tablet',
		strength: '850mg',
		unit: 'tablet',
		schedule: 'Rx',
		description: 'Helps manage blood sugar for diabetes!',
		units_per_pack: 60,
		price: 15.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 700,
		expiry_date: new Date('2025-09-05'),
		purchase_date: new Date('2024-03-01'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Antidiabetics'],
	},
	{
		name: 'Amlodipine',
		manufacturer: 'BloodPressRx',
		generic_name: 'Amlodipine besylate',
		formulation: 'Tablet',
		strength: '5mg',
		unit: 'tablet',
		schedule: 'Rx',
		description: 'Keeps that blood pressure nice and steady!',
		units_per_pack: 90,
		price: 28.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 550,
		expiry_date: new Date('2026-04-22'),
		purchase_date: new Date('2024-02-10'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Cardiac Care'],
	},
	{
		name: 'Ranitidine',
		manufacturer: 'AcidBlockers',
		generic_name: 'Ranitidine HCl',
		formulation: 'Tablet',
		strength: '150mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Stops heartburn before it even starts!',
		units_per_pack: 60,
		price: 9.45,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 120,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 900,
		expiry_date: new Date('2025-07-12'),
		purchase_date: new Date('2024-04-25'),
		supplierName: 'Pfizer India',
		categoryNames: ['Antacids'],
	},
	{
		name: 'Dextromethorphan Syrup',
		manufacturer: 'CoughEase',
		generic_name: 'Dextromethorphan HBr',
		formulation: 'Syrup',
		strength: '15mg/5mL',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Kicks that cough to the curb!',
		units_per_pack: 1,
		price: 8.7,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2026-02-08'),
		purchase_date: new Date('2024-05-10'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'Pseudoephedrine',
		manufacturer: 'NasalClear',
		generic_name: 'Pseudoephedrine HCl',
		formulation: 'Tablet',
		strength: '30mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Gets your nose breathing clear again!',
		units_per_pack: 24,
		price: 6.8,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1000,
		expiry_date: new Date('2025-10-01'),
		purchase_date: new Date('2024-04-05'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'Multivitamin Adult',
		manufacturer: 'VitaBoost',
		generic_name: 'Multivitamin complex',
		formulation: 'Tablet',
		strength: 'N/A',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'All the daily vitamins you need, in one!',
		units_per_pack: 90,
		price: 11.2,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 750,
		expiry_date: new Date('2027-05-15'),
		purchase_date: new Date('2024-06-10'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Vitamin D3',
		manufacturer: 'BoneStrong',
		generic_name: 'Cholecalciferol',
		formulation: 'Softgel',
		strength: '1000 IU',
		unit: 'softgel',
		schedule: 'OTC',
		description: 'Great for strong bones and a happy immune system!',
		units_per_pack: 120,
		price: 9.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1100,
		expiry_date: new Date('2026-11-01'),
		purchase_date: new Date('2024-05-25'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Folic Acid',
		manufacturer: 'PrenatalEssentials',
		generic_name: 'Folic Acid',
		formulation: 'Tablet',
		strength: '1mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Helps your cells grow healthy and strong!',
		units_per_pack: 90,
		price: 4.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1300,
		expiry_date: new Date('2025-08-28'),
		purchase_date: new Date('2024-03-20'),
		supplierName: 'Pfizer India',
		categoryNames: ['Vitamins & Supplements', "Women's Health"],
	},
	{
		name: 'Iron Supplement',
		manufacturer: 'BloodBuilder',
		generic_name: 'Ferrous sulfate',
		formulation: 'Capsule',
		strength: '65mg',
		unit: 'capsule',
		schedule: 'OTC',
		description: 'Boosts your iron to keep you feeling great!',
		units_per_pack: 60,
		price: 7.8,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 850,
		expiry_date: new Date('2026-03-05'),
		purchase_date: new Date('2024-04-15'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Magnesium Citrate',
		manufacturer: 'CalmRelax',
		generic_name: 'Magnesium citrate',
		formulation: 'Powder',
		strength: '300mg',
		unit: 'sachet',
		schedule: 'OTC',
		description: 'Helps your muscles relax and tummy feel good!',
		units_per_pack: 30,
		price: 10.25,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 70,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 650,
		expiry_date: new Date('2027-02-10'),
		purchase_date: new Date('2024-06-05'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Calcium Carbonate',
		manufacturer: 'CalciPlus',
		generic_name: 'Calcium carbonate',
		formulation: 'Chewable',
		strength: '600mg',
		unit: 'chewable tab',
		schedule: 'OTC',
		description: 'For strong bones and calming indigestion!',
		units_per_pack: 60,
		price: 8.9,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 120,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 950,
		expiry_date: new Date('2026-09-19'),
		purchase_date: new Date('2024-03-25'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Vitamins & Supplements', 'Antacids'],
	},
	{
		name: 'Probiotic Blend',
		manufacturer: 'GutHealth',
		generic_name: 'Lactobacillus blend',
		formulation: 'Capsule',
		strength: '5 Billion CFU',
		unit: 'capsule',
		schedule: 'OTC',
		description: 'Keeps your gut happy and healthy!',
		units_per_pack: 30,
		price: 19.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2025-12-31'),
		purchase_date: new Date('2024-05-05'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Omega-3 Fish Oil',
		manufacturer: 'HeartSmart',
		generic_name: 'EPA/DHA',
		formulation: 'Softgel',
		strength: '1000mg',
		unit: 'softgel',
		schedule: 'OTC',
		description: 'Super important for a healthy heart and brain!',
		units_per_pack: 60,
		price: 14.75,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 70,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 500,
		expiry_date: new Date('2026-07-07'),
		purchase_date: new Date('2024-04-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['Vitamins & Supplements', 'Cardiac Care'],
	},
	{
		name: 'Topical Hydrocortisone',
		manufacturer: 'SkinRelief',
		generic_name: 'Hydrocortisone',
		formulation: 'Cream',
		strength: '1%',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Stops that annoying itching and rashes!',
		units_per_pack: 1,
		price: 6.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 90,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 700,
		expiry_date: new Date('2025-11-11'),
		purchase_date: new Date('2024-03-30'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Dermatology'],
	},
	{
		name: 'Antifungal Cream',
		manufacturer: 'FungiGone',
		generic_name: 'Clotrimazole',
		formulation: 'Cream',
		strength: '1%',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Zaps those pesky fungal skin infections!',
		units_per_pack: 1,
		price: 9.2,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 70,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 550,
		expiry_date: new Date('2026-01-25'),
		purchase_date: new Date('2024-05-15'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Dermatology'],
	},
	{
		name: 'Bacitracin Ointment',
		manufacturer: 'WoundHeal',
		generic_name: 'Bacitracin',
		formulation: 'Ointment',
		strength: '500 units/g',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Keeps minor cuts from getting infected!',
		units_per_pack: 1,
		price: 4.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1200,
		expiry_date: new Date('2027-04-01'),
		purchase_date: new Date('2024-06-01'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['First Aid', 'Antibiotics'],
	},
	{
		name: 'Hydrogen Peroxide',
		manufacturer: 'DisinfectAll',
		generic_name: 'Hydrogen Peroxide',
		formulation: 'Liquid',
		strength: '3%',
		unit: 'mL',
		schedule: 'OTC',
		description: 'A bubbly way to clean minor cuts!',
		units_per_pack: 1,
		price: 2.75,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1800,
		expiry_date: new Date('2025-09-10'),
		purchase_date: new Date('2024-03-01'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Rubbing Alcohol',
		manufacturer: 'CleanHands',
		generic_name: 'Isopropyl Alcohol',
		formulation: 'Liquid',
		strength: '70%',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Perfect for quick cleaning and disinfecting!',
		units_per_pack: 1,
		price: 3.1,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1600,
		expiry_date: new Date('2026-05-03'),
		purchase_date: new Date('2024-05-05'),
		supplierName: 'Pfizer India',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Adhesive Bandages',
		manufacturer: 'FirstAidCo',
		generic_name: 'Assorted bandages',
		formulation: 'Box',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: "Stick 'em on for quick protection of minor cuts!",
		units_per_pack: 100,
		price: 5.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1000,
		expiry_date: new Date('2028-01-01'),
		purchase_date: new Date('2024-06-15'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Sterile Gauze Pads',
		manufacturer: 'MedSupplies',
		generic_name: 'Sterile gauze',
		formulation: 'Pack',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Soft pads for covering wounds!',
		units_per_pack: 25,
		price: 7.2,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 800,
		expiry_date: new Date('2027-08-14'),
		purchase_date: new Date('2024-02-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Medical Tape',
		manufacturer: 'SecureFix',
		generic_name: 'Surgical tape',
		formulation: 'Roll',
		strength: 'N/A',
		unit: 'roll',
		schedule: 'OTC',
		description: 'Keeps your bandages right where they belong!',
		units_per_pack: 1,
		price: 3.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1500,
		expiry_date: new Date('2029-02-01'),
		purchase_date: new Date('2024-01-01'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['First Aid'],
	},
	{
		name: 'Digital Thermometer',
		manufacturer: 'TempCheck',
		generic_name: 'Digital thermometer',
		formulation: 'Device',
		strength: 'N/A',
		unit: 'each',
		schedule: 'OTC',
		description: 'Get a quick read on your temperature!',
		units_per_pack: 1,
		price: 14.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 300,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-05-10'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Medical Devices'],
	},
	{
		name: 'Blood Pressure Monitor',
		manufacturer: 'BPTrack',
		generic_name: 'Automatic BP monitor',
		formulation: 'Device',
		strength: 'N/A',
		unit: 'each',
		schedule: 'OTC',
		description: 'Easily check your blood pressure at home!',
		units_per_pack: 1,
		price: 45.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 20,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 150,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-04-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['Medical Devices', 'Cardiac Care'],
	},
	{
		name: 'Glucose Test Strips',
		manufacturer: 'GlucoSense',
		generic_name: 'Glucose strips',
		formulation: 'Box',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Essential for keeping track of your blood sugar!',
		units_per_pack: 50,
		price: 29.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 40,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 250,
		expiry_date: new Date('2026-03-01'),
		purchase_date: new Date('2024-06-01'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Medical Devices', 'Antidiabetics'],
	},
	{
		name: 'Lancets',
		manufacturer: 'PrickSafe',
		generic_name: 'Blood lancets',
		formulation: 'Box',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Tiny tools for quick blood samples!',
		units_per_pack: 100,
		price: 8.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 600,
		expiry_date: new Date('2028-06-01'),
		purchase_date: new Date('2024-01-15'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Medical Devices', 'Antidiabetics'],
	},
	{
		name: 'Insulin Syringes',
		manufacturer: 'InjectEase',
		generic_name: 'Insulin syringes',
		formulation: 'Box',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Easy-to-use syringes for insulin!',
		units_per_pack: 100,
		price: 11.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 60,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2027-07-01'),
		purchase_date: new Date('2024-03-10'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Medical Devices', 'Antidiabetics'],
	},
	{
		name: 'Eye Drops (Saline)',
		manufacturer: 'ClearVision',
		generic_name: 'Sodium Chloride',
		formulation: 'Solution',
		strength: '0.9%',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Soothes and moisturizes dry eyes!',
		units_per_pack: 1,
		price: 6.75,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 700,
		expiry_date: new Date('2025-10-20'),
		purchase_date: new Date('2024-05-20'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Ear Wax Removal Kit',
		manufacturer: 'HearClear',
		generic_name: 'Carbamide Peroxide',
		formulation: 'Kit',
		strength: '6.5%',
		unit: 'kit',
		schedule: 'OTC',
		description: 'Helps get rid of stubborn earwax!',
		units_per_pack: 1,
		price: 10.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 40,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 350,
		expiry_date: new Date('2026-04-15'),
		purchase_date: new Date('2024-06-10'),
		supplierName: 'Pfizer India',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Oral Rehydration Salts',
		manufacturer: 'ReHydrate',
		generic_name: 'Electrolyte blend',
		formulation: 'Sachet',
		strength: 'N/A',
		unit: 'sachet',
		schedule: 'OTC',
		description: "Replenishes what your body needs when you're feeling down!",
		units_per_pack: 10,
		price: 4.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 900,
		expiry_date: new Date('2027-01-05'),
		purchase_date: new Date('2024-02-01'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Electrolyte Solution',
		manufacturer: 'ElectroLyte',
		generic_name: 'Electrolyte blend',
		formulation: 'Liquid',
		strength: 'N/A',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Great for staying hydrated and feeling balanced!',
		units_per_pack: 1,
		price: 7.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 500,
		expiry_date: new Date('2026-08-01'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Antacid Chewables',
		manufacturer: 'TummySoothe',
		generic_name: 'Calcium Carbonate',
		formulation: 'Chewable',
		strength: '750mg',
		unit: 'chewable tab',
		schedule: 'OTC',
		description: 'Chewy relief for heartburn and indigestion!',
		units_per_pack: 60,
		price: 5.2,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1100,
		expiry_date: new Date('2025-11-08'),
		purchase_date: new Date('2024-04-10'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Antacids'],
	},
	{
		name: 'Laxative Tablets',
		manufacturer: 'BowelEase',
		generic_name: 'Bisacodyl',
		formulation: 'Tablet',
		strength: '5mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: "Helps get things moving when you're a bit stuck!",
		units_per_pack: 25,
		price: 6.9,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 800,
		expiry_date: new Date('2026-02-28'),
		purchase_date: new Date('2024-03-05'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Anti-Diarrheal Caplets',
		manufacturer: 'StopRuns',
		generic_name: 'Loperamide HCl',
		formulation: 'Caplet',
		strength: '2mg',
		unit: 'caplet',
		schedule: 'OTC',
		description: 'Puts a stop to diarrhea symptoms fast!',
		units_per_pack: 12,
		price: 7.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 90,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 700,
		expiry_date: new Date('2025-09-22'),
		purchase_date: new Date('2024-04-20'),
		supplierName: 'Pfizer India',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Motion Sickness Pills',
		manufacturer: 'TravelCalm',
		generic_name: 'Dimenhydrinate',
		formulation: 'Tablet',
		strength: '50mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Keeps you from feeling queasy on the go!',
		units_per_pack: 12,
		price: 8.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 60,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 450,
		expiry_date: new Date('2027-03-10'),
		purchase_date: new Date('2024-05-10'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Sleep Aid Tablets',
		manufacturer: 'DreamWell',
		generic_name: 'Diphenhydramine HCl',
		formulation: 'Tablet',
		strength: '25mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Helps you drift off to sleep at night!',
		units_per_pack: 24,
		price: 12.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 40,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 300,
		expiry_date: new Date('2026-06-01'),
		purchase_date: new Date('2024-02-15'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Melatonin',
		manufacturer: 'NightRest',
		generic_name: 'Melatonin',
		formulation: 'Tablet',
		strength: '5mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'A natural way to help you get some rest!',
		units_per_pack: 60,
		price: 9.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 600,
		expiry_date: new Date('2025-12-15'),
		purchase_date: new Date('2024-05-01'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Sore Throat Lozenges',
		manufacturer: 'SootheThroat',
		generic_name: 'Benzocaine',
		formulation: 'Lozenge',
		strength: 'N/A',
		unit: 'lozenge',
		schedule: 'OTC',
		description: 'Sweet relief for a scratchy throat!',
		units_per_pack: 18,
		price: 4.75,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1400,
		expiry_date: new Date('2027-04-20'),
		purchase_date: new Date('2024-06-01'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'Cough Drops',
		manufacturer: 'BreathEasy',
		generic_name: 'Menthol',
		formulation: 'Lozenge',
		strength: 'N/A',
		unit: 'lozenge',
		schedule: 'OTC',
		description: 'Freshens your breath and calms that cough!',
		units_per_pack: 30,
		price: 3.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 250,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1700,
		expiry_date: new Date('2026-09-01'),
		purchase_date: new Date('2024-03-15'),
		supplierName: 'Pfizer India',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'VapoRub',
		manufacturer: 'ChestClear',
		generic_name: 'Camphor, Menthol, Eucalyptus',
		formulation: 'Ointment',
		strength: 'N/A',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Rub it on for soothing cough and congestion relief!',
		units_per_pack: 1,
		price: 6.2,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 850,
		expiry_date: new Date('2025-07-25'),
		purchase_date: new Date('2024-04-20'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'Nasal Saline Spray',
		manufacturer: 'NoseRinse',
		generic_name: 'Sodium Chloride',
		formulation: 'Spray',
		strength: '0.9%',
		unit: 'mL',
		schedule: 'OTC',
		description: 'A simple spray to clear out your nose!',
		units_per_pack: 1,
		price: 5.8,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 120,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 950,
		expiry_date: new Date('2026-01-10'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'Hand Sanitizer',
		manufacturer: 'GermAway',
		generic_name: 'Ethyl Alcohol',
		formulation: 'Gel',
		strength: '70%',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Keep those hands clean and germ-free!',
		units_per_pack: 1,
		price: 4.25,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1600,
		expiry_date: new Date('2027-05-01'),
		purchase_date: new Date('2024-06-10'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Face Masks (Disposable)',
		manufacturer: 'ProtectYou',
		generic_name: 'Disposable face masks',
		formulation: 'Box',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Handy masks for staying safe and protected!',
		units_per_pack: 50,
		price: 15.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 500,
		expiry_date: new Date('2028-03-01'),
		purchase_date: new Date('2024-01-01'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Nitrile Gloves',
		manufacturer: 'SafeTouch',
		generic_name: 'Nitrile gloves',
		formulation: 'Box',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Protect your hands with these comfy gloves!',
		units_per_pack: 100,
		price: 18.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 60,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2029-01-01'),
		purchase_date: new Date('2024-02-15'),
		supplierName: 'Pfizer India',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'First Aid Kit (Basic)',
		manufacturer: 'EmergencyReady',
		generic_name: 'Basic first aid supplies',
		formulation: 'Kit',
		strength: 'N/A',
		unit: 'kit',
		schedule: 'OTC',
		description: 'Your essential kit for minor boo-boos!',
		units_per_pack: 1,
		price: 25.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 30,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 200,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-03-01'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Sunscreen',
		manufacturer: 'SunGuard',
		generic_name: 'Zinc Oxide, Titanium Dioxide',
		formulation: 'Lotion',
		strength: 'SPF 30',
		unit: 'mL',
		schedule: 'OTC',
		description: "Keeps your skin safe from the sun's rays!",
		units_per_pack: 1,
		price: 10.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 600,
		expiry_date: new Date('2026-07-01'),
		purchase_date: new Date('2024-05-20'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Personal Care', 'Dermatology'],
	},
	{
		name: 'Insect Repellent',
		manufacturer: 'BugOff',
		generic_name: 'DEET',
		formulation: 'Spray',
		strength: '25%',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Spritz it on to keep those annoying bugs away!',
		units_per_pack: 1,
		price: 9.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 90,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 700,
		expiry_date: new Date('2025-08-05'),
		purchase_date: new Date('2024-04-10'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Personal Care'],
	},
	{
		name: 'After-Bite Soother',
		manufacturer: 'ItchRelief',
		generic_name: 'Pramoxine HCl',
		formulation: 'Cream',
		strength: '1%',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Soothes that itch after an insect bite!',
		units_per_pack: 1,
		price: 5.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 800,
		expiry_date: new Date('2027-02-18'),
		purchase_date: new Date('2024-06-01'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Personal Care', 'Dermatology'],
	},
	{
		name: 'Burn Relief Gel',
		manufacturer: 'CoolBurn',
		generic_name: 'Aloe Vera',
		formulation: 'Gel',
		strength: 'N/A',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Cools and calms minor burns!',
		units_per_pack: 1,
		price: 7.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 70,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 500,
		expiry_date: new Date('2026-05-20'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['First Aid', 'Dermatology'],
	},
	{
		name: 'Cold Pack (Instant)',
		manufacturer: 'IceQuick',
		generic_name: 'Ammonium Nitrate',
		formulation: 'Pack',
		strength: 'N/A',
		unit: 'pack',
		schedule: 'OTC',
		description: 'Instant chill for bumps and bruises!',
		units_per_pack: 1,
		price: 3.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1000,
		expiry_date: new Date('2028-04-01'),
		purchase_date: new Date('2024-03-01'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Hot Pack (Reusable)',
		manufacturer: 'WarmComfort',
		generic_name: 'Sodium Acetate',
		formulation: 'Pack',
		strength: 'N/A',
		unit: 'pack',
		schedule: 'OTC',
		description: 'Warm relief you can use again and again!',
		units_per_pack: 1,
		price: 8.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 60,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2029-03-01'),
		purchase_date: new Date('2024-02-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Heating Pad (Electric)',
		manufacturer: 'HeatTherapy',
		generic_name: 'Electric heating element',
		formulation: 'Device',
		strength: 'N/A',
		unit: 'each',
		schedule: 'OTC',
		description: 'Provides steady warmth for aches!',
		units_per_pack: 1,
		price: 29.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 15,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 100,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-04-15'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Medical Devices', 'Pain Relief'],
	},
	{
		name: 'Vaporizer/Humidifier',
		manufacturer: 'AirEase',
		generic_name: 'Water vaporization',
		formulation: 'Device',
		strength: 'N/A',
		unit: 'each',
		schedule: 'OTC',
		description: 'Puts moisture in the air for easier breathing!',
		units_per_pack: 1,
		price: 39.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 10,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 80,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Medical Devices', 'Couch & Cold'],
	},
	{
		name: 'Nebulizer',
		manufacturer: 'BreatheEasy',
		generic_name: 'Air compressor',
		formulation: 'Device',
		strength: 'N/A',
		unit: 'each',
		schedule: 'Rx',
		description: 'Helps deliver medicine as a fine mist!',
		units_per_pack: 1,
		price: 65.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 5,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 50,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-03-20'),
		supplierName: 'Pfizer India',
		categoryNames: ['Medical Devices'],
	},
	{
		name: 'Glucose Tablets',
		manufacturer: 'EnergyBoost',
		generic_name: 'Dextrose',
		formulation: 'Tablet',
		strength: '4g',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Quick sugar boost when you need it!',
		units_per_pack: 10,
		price: 6.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 90,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 700,
		expiry_date: new Date('2026-10-01'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Antidiabetics'],
	},
	{
		name: 'Protein Powder',
		manufacturer: 'MuscleMax',
		generic_name: 'Whey protein isolate',
		formulation: 'Powder',
		strength: '25g/serving',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Great for building and repairing muscles!',
		units_per_pack: 1,
		price: 28.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 40,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 250,
		expiry_date: new Date('2027-06-01'),
		purchase_date: new Date('2024-04-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Meal Replacement Shake',
		manufacturer: 'DietSmart',
		generic_name: 'Protein, vitamins, minerals',
		formulation: 'Powder',
		strength: 'N/A',
		unit: 'serving',
		schedule: 'OTC',
		description: 'A quick and easy way to get your nutrients!',
		units_per_pack: 14,
		price: 22.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 300,
		expiry_date: new Date('2026-11-01'),
		purchase_date: new Date('2024-03-25'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Fiber Supplement',
		manufacturer: 'DigestiHealth',
		generic_name: 'Psyllium husk',
		formulation: 'Powder',
		strength: 'N/A',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Helps keep your digestion running smoothly!',
		units_per_pack: 1,
		price: 13.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 60,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2025-12-01'),
		purchase_date: new Date('2024-05-15'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Vitamins & Supplements'],
	},
	{
		name: 'Biotin',
		manufacturer: 'HairSkinNails',
		generic_name: 'Biotin',
		formulation: 'Capsule',
		strength: '10000mcg',
		unit: 'capsule',
		schedule: 'OTC',
		description: 'For fabulous hair, skin, and nails!',
		units_per_pack: 60,
		price: 16.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 350,
		expiry_date: new Date('2027-01-15'),
		purchase_date: new Date('2024-06-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['Vitamins & Supplements', 'Personal Care'],
	},
	{
		name: 'CoQ10',
		manufacturer: 'CardioEnergy',
		generic_name: 'Coenzyme Q10',
		formulation: 'Softgel',
		strength: '100mg',
		unit: 'softgel',
		schedule: 'OTC',
		description: 'Supports a healthy heart and energy levels!',
		units_per_pack: 30,
		price: 24.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 30,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 200,
		expiry_date: new Date('2026-08-20'),
		purchase_date: new Date('2024-02-20'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Vitamins & Supplements', 'Cardiac Care'],
	},
	{
		name: 'Zinc Lozenges',
		manufacturer: 'ImmuneGuard',
		generic_name: 'Zinc gluconate',
		formulation: 'Lozenge',
		strength: '15mg',
		unit: 'lozenge',
		schedule: 'OTC',
		description: 'Gives your immune system a little boost for colds!',
		units_per_pack: 18,
		price: 8.2,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 120,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 900,
		expiry_date: new Date('2025-09-15'),
		purchase_date: new Date('2024-05-05'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Vitamins & Supplements', 'Couch & Cold'],
	},
	{
		name: 'Vitamin C',
		manufacturer: 'ImmuneBoost',
		generic_name: 'Ascorbic Acid',
		formulation: 'Tablet',
		strength: '1000mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Your daily dose for a strong immune system!',
		units_per_pack: 100,
		price: 10.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1000,
		expiry_date: new Date('2027-03-01'),
		purchase_date: new Date('2024-06-10'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Vitamins & Supplements', 'Couch & Cold'],
	},
	{
		name: 'Echinacea Extract',
		manufacturer: 'ColdDefense',
		generic_name: 'Echinacea purpurea',
		formulation: 'Liquid',
		strength: 'N/A',
		unit: 'mL',
		schedule: 'OTC',
		description: 'A herbal helper for your immune system!',
		units_per_pack: 1,
		price: 11.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 70,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 500,
		expiry_date: new Date('2026-04-05'),
		purchase_date: new Date('2024-05-20'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Vitamins & Supplements', 'Couch & Cold'],
	},
	{
		name: 'Elderberry Syrup',
		manufacturer: 'FluShield',
		generic_name: 'Sambucus nigra',
		formulation: 'Syrup',
		strength: 'N/A',
		unit: 'mL',
		schedule: 'OTC',
		description: 'A sweet way to support your immunity, especially during flu season!',
		units_per_pack: 1,
		price: 13.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 60,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 450,
		expiry_date: new Date('2025-11-01'),
		purchase_date: new Date('2024-04-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['Vitamins & Supplements', 'Couch & Cold'],
	},
	{
		name: 'Gaviscon Liquid',
		manufacturer: 'HeartburnRelief',
		generic_name: 'Aluminum hydroxide',
		formulation: 'Liquid',
		strength: 'N/A',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Quick relief for heartburn and indigestion!',
		units_per_pack: 1,
		price: 11.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 600,
		expiry_date: new Date('2026-02-14'),
		purchase_date: new Date('2024-03-10'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Antacids'],
	},
	{
		name: 'Pepto-Bismol',
		manufacturer: 'StomachSoothe',
		generic_name: 'Bismuth subsalicylate',
		formulation: 'Liquid',
		strength: 'N/A',
		unit: 'mL',
		schedule: 'OTC',
		description: "Your tummy's best friend for diarrhea and upset stomachs!",
		units_per_pack: 1,
		price: 9.75,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 750,
		expiry_date: new Date('2025-10-10'),
		purchase_date: new Date('2024-04-25'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Antacids'],
	},
	{
		name: 'Imodium',
		manufacturer: 'DiarrheaStop',
		generic_name: 'Loperamide HCl',
		formulation: 'Caplet',
		strength: '2mg',
		unit: 'caplet',
		schedule: 'OTC',
		description: 'Puts a quick stop to diarrhea, so you can get on with your day!',
		units_per_pack: 6,
		price: 10.2,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 70,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 500,
		expiry_date: new Date('2027-01-22'),
		purchase_date: new Date('2024-06-01'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Dramamine',
		manufacturer: 'MotionSickness',
		generic_name: 'Dimenhydrinate',
		formulation: 'Tablet',
		strength: '50mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Keeps you from feeling queasy on the go!',
		units_per_pack: 8,
		price: 9.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2026-07-01'),
		purchase_date: new Date('2024-05-10'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Benadryl Allergy',
		manufacturer: 'AllergyDrowsy',
		generic_name: 'Diphenhydramine HCl',
		formulation: 'Tablet',
		strength: '25mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'An old reliable for allergy relief, but it might make you sleepy!',
		units_per_pack: 24,
		price: 8.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 800,
		expiry_date: new Date('2025-12-05'),
		purchase_date: new Date('2024-03-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['Antihistamines'],
	},
	{
		name: 'Claritin',
		manufacturer: 'AllergyNonDrowsy',
		generic_name: 'Loratadine',
		formulation: 'Tablet',
		strength: '10mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: "Allergy relief that won't make you drowsy!",
		units_per_pack: 30,
		price: 14.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 600,
		expiry_date: new Date('2026-09-10'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Antihistamines'],
	},
	{
		name: 'Zyrtec',
		manufacturer: 'AllergyFast',
		generic_name: 'Cetirizine HCl',
		formulation: 'Tablet',
		strength: '10mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Fast-acting allergy relief!',
		units_per_pack: 30,
		price: 13.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 650,
		expiry_date: new Date('2027-02-01'),
		purchase_date: new Date('2024-06-10'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Antihistamines'],
	},
	{
		name: 'Flonase Nasal Spray',
		manufacturer: 'NasalAllergy',
		generic_name: 'Fluticasone propionate',
		formulation: 'Spray',
		strength: '50mcg/spray',
		unit: 'spray',
		schedule: 'OTC',
		description: 'Allergy nasal spray!',
		units_per_pack: 1,
		price: 19.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 40,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 300,
		expiry_date: new Date('2026-05-01'),
		purchase_date: new Date('2024-04-15'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Antihistamines'],
	},
	{
		name: 'Afrin Nasal Spray',
		manufacturer: 'Decongestant',
		generic_name: 'Oxymetazoline HCl',
		formulation: 'Spray',
		strength: '0.05%',
		unit: 'spray',
		schedule: 'OTC',
		description: 'Nasal decongestant!',
		units_per_pack: 1,
		price: 7.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 700,
		expiry_date: new Date('2025-11-15'),
		purchase_date: new Date('2024-03-20'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'Saline Nasal Rinse Kit',
		manufacturer: 'SinusClear',
		generic_name: 'Sodium chloride',
		formulation: 'Kit',
		strength: 'N/A',
		unit: 'kit',
		schedule: 'OTC',
		description: 'Nasal irrigation for sinus relief!',
		units_per_pack: 1,
		price: 16.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 30,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 250,
		expiry_date: new Date('2028-01-01'),
		purchase_date: new Date('2024-02-10'),
		supplierName: 'Pfizer India',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'Cough Suppressant Pills',
		manufacturer: 'DryCoughRelief',
		generic_name: 'Dextromethorphan HBr',
		formulation: 'Tablet',
		strength: '15mg',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Suppresses dry cough!',
		units_per_pack: 20,
		price: 7.8,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 600,
		expiry_date: new Date('2026-03-18'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Couch & Cold'],
	},
	{
		name: 'Pediatric Ibuprofen',
		manufacturer: 'KidRelief',
		generic_name: 'Ibuprofen',
		formulation: 'Suspension',
		strength: '100mg/5mL',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Pain and fever relief for little ones!',
		units_per_pack: 1,
		price: 8.5,
		tax_rate: 0.05,
		discount: 0.06,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 600,
		expiry_date: new Date('2026-04-01'),
		purchase_date: new Date('2024-05-15'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Pain Relief', 'Antipyretics', 'Pediatric Care'],
	},
	{
		name: 'Pediatric Paracetamol',
		manufacturer: 'TinyTots',
		generic_name: 'Acetaminophen',
		formulation: 'Syrup',
		strength: '120mg/5mL',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Gentle fever and pain relief for kids!',
		units_per_pack: 1,
		price: 7.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 120,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 800,
		expiry_date: new Date('2026-06-15'),
		purchase_date: new Date('2024-06-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Pain Relief', 'Antipyretics', 'Pediatric Care'],
	},
	{
		name: 'Children’s Multivitamin',
		manufacturer: 'GrowEasy',
		generic_name: 'Multivitamin complex',
		formulation: 'Gummy',
		strength: 'N/A',
		unit: 'gummy',
		schedule: 'OTC',
		description: 'Yummy vitamins to help kids grow strong!',
		units_per_pack: 60,
		price: 12.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 80,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 500,
		expiry_date: new Date('2027-02-01'),
		purchase_date: new Date('2024-04-20'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Vitamins & Supplements', 'Pediatric Care'],
	},
	{
		name: 'Pediatric Cough Syrup',
		manufacturer: 'LittleLungs',
		generic_name: 'Dextromethorphan',
		formulation: 'Syrup',
		strength: '5mg/5mL',
		unit: 'mL',
		schedule: 'OTC',
		description: 'Soothes coughs for children!',
		units_per_pack: 1,
		price: 9.25,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 90,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 700,
		expiry_date: new Date('2026-03-10'),
		purchase_date: new Date('2024-05-10'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Couch & Cold', 'Pediatric Care'],
	},
	{
		name: 'Baby Diaper Cream',
		manufacturer: 'SoftSkin',
		generic_name: 'Zinc Oxide',
		formulation: 'Cream',
		strength: '40%',
		unit: 'gram',
		schedule: 'OTC',
		description: 'Protects and heals baby’s delicate skin!',
		units_per_pack: 1,
		price: 6.8,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 900,
		expiry_date: new Date('2025-12-20'),
		purchase_date: new Date('2024-03-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['Dermatology', 'Pediatric Care'],
	},
	{
		name: 'Oral Contraceptive Pills',
		manufacturer: 'FemCare',
		generic_name: 'Ethinyl estradiol, Levonorgestrel',
		formulation: 'Tablet',
		strength: '0.03mg/0.15mg',
		unit: 'tablet',
		schedule: 'Rx',
		description: 'Reliable birth control for women!',
		units_per_pack: 28,
		price: 15.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2026-08-01'),
		purchase_date: new Date('2024-04-15'),
		supplierName: 'Cipla Ltd',
		categoryNames: ["Women's Health"],
	},
	{
		name: 'Sanitary Pads',
		manufacturer: 'ComfortCare',
		generic_name: 'Absorbent pads',
		formulation: 'Pack',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Comfortable protection for menstrual cycles!',
		units_per_pack: 10,
		price: 4.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1500,
		expiry_date: new Date('2028-01-01'),
		purchase_date: new Date('2024-06-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ["Women's Health", 'Personal Care'],
	},
	{
		name: 'Tampons',
		manufacturer: 'EasyFlow',
		generic_name: 'Absorbent tampons',
		formulation: 'Box',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Convenient menstrual protection!',
		units_per_pack: 20,
		price: 6.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1000,
		expiry_date: new Date('2027-06-01'),
		purchase_date: new Date('2024-05-20'),
		supplierName: "Dr. Reddy's",
		categoryNames: ["Women's Health", 'Personal Care'],
	},
	{
		name: 'Prenatal Vitamins',
		manufacturer: 'MomToBe',
		generic_name: 'Multivitamin with Folic Acid',
		formulation: 'Tablet',
		strength: 'N/A',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Supports healthy pregnancy and fetal development!',
		units_per_pack: 90,
		price: 18.99,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 60,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 450,
		expiry_date: new Date('2026-09-15'),
		purchase_date: new Date('2024-03-10'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Vitamins & Supplements', "Women's Health"],
	},
	{
		name: 'Men’s Multivitamin',
		manufacturer: 'VitalMan',
		generic_name: 'Multivitamin complex',
		formulation: 'Tablet',
		strength: 'N/A',
		unit: 'tablet',
		schedule: 'OTC',
		description: 'Tailored nutrients for men’s health!',
		units_per_pack: 90,
		price: 14.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 70,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 500,
		expiry_date: new Date('2027-01-10'),
		purchase_date: new Date('2024-04-01'),
		supplierName: 'Pfizer India',
		categoryNames: ['Vitamins & Supplements', "Men's Health"],
	},
	{
		name: 'Prostate Health Supplement',
		manufacturer: 'ProstaCare',
		generic_name: 'Saw Palmetto, Zinc',
		formulation: 'Capsule',
		strength: 'N/A',
		unit: 'capsule',
		schedule: 'OTC',
		description: 'Supports prostate health in men!',
		units_per_pack: 60,
		price: 22.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 40,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 300,
		expiry_date: new Date('2026-05-01'),
		purchase_date: new Date('2024-05-15'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Vitamins & Supplements', "Men's Health"],
	},
	{
		name: 'Sertraline',
		manufacturer: 'MindBalance',
		generic_name: 'Sertraline HCl',
		formulation: 'Tablet',
		strength: '50mg',
		unit: 'tablet',
		schedule: 'Rx',
		description: 'Helps manage depression and anxiety!',
		units_per_pack: 30,
		price: 25.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 400,
		expiry_date: new Date('2026-07-20'),
		purchase_date: new Date('2024-03-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ['Mental Health'],
	},
	{
		name: 'Lorazepam',
		manufacturer: 'CalmMind',
		generic_name: 'Lorazepam',
		formulation: 'Tablet',
		strength: '1mg',
		unit: 'tablet',
		schedule: 'Rx',
		description: 'For short-term anxiety relief!',
		units_per_pack: 30,
		price: 20.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 40,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 350,
		expiry_date: new Date('2026-02-01'),
		purchase_date: new Date('2024-04-10'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Mental Health'],
	},
	{
		name: 'Fluoxetine',
		manufacturer: 'MoodLift',
		generic_name: 'Fluoxetine HCl',
		formulation: 'Capsule',
		strength: '20mg',
		unit: 'capsule',
		schedule: 'Rx',
		description: 'Supports mental health for depression and OCD!',
		units_per_pack: 30,
		price: 23.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 50,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 450,
		expiry_date: new Date('2026-10-01'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Mental Health'],
	},
	{
		name: 'Incontinence Pads',
		manufacturer: 'DryComfort',
		generic_name: 'Absorbent pads',
		formulation: 'Pack',
		strength: 'N/A',
		unit: 'count',
		schedule: 'OTC',
		description: 'Discreet protection for bladder control!',
		units_per_pack: 20,
		price: 10.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 100,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 800,
		expiry_date: new Date('2028-03-01'),
		purchase_date: new Date('2024-06-10'),
		supplierName: 'Pfizer India',
		categoryNames: ['Personal Care'],
	},
	{
		name: 'Antiseptic Wipes',
		manufacturer: 'CleanSafe',
		generic_name: 'Alcohol wipes',
		formulation: 'Pack',
		strength: '70%',
		unit: 'count',
		schedule: 'OTC',
		description: 'Handy wipes for quick disinfection!',
		units_per_pack: 50,
		price: 5.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 150,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1200,
		expiry_date: new Date('2027-04-01'),
		purchase_date: new Date('2024-03-15'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Elastic Bandage',
		manufacturer: 'SupportWrap',
		generic_name: 'Elastic bandage',
		formulation: 'Roll',
		strength: 'N/A',
		unit: 'roll',
		schedule: 'OTC',
		description: 'Supports sprains and strains!',
		units_per_pack: 1,
		price: 4.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1000,
		expiry_date: new Date('2029-01-01'),
		purchase_date: new Date('2024-05-01'),
		supplierName: 'Sun Pharma',
		categoryNames: ['First Aid'],
	},
	{
		name: 'Wrist Brace',
		manufacturer: 'StableGrip',
		generic_name: 'Wrist support',
		formulation: 'Device',
		strength: 'N/A',
		unit: 'each',
		schedule: 'OTC',
		description: 'Stabilizes wrist for pain relief!',
		units_per_pack: 1,
		price: 15.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 30,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 200,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-04-20'),
		supplierName: "Dr. Reddy's",
		categoryNames: ['Medical Devices', 'Pain Relief'],
	},
	{
		name: 'Knee Support',
		manufacturer: 'JointEase',
		generic_name: 'Knee brace',
		formulation: 'Device',
		strength: 'N/A',
		unit: 'each',
		schedule: 'OTC',
		description: 'Provides support for knee injuries!',
		units_per_pack: 1,
		price: 20.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 25,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 150,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-06-01'),
		supplierName: 'Abbott Healthcare',
		categoryNames: ['Medical Devices', 'Pain Relief'],
	},
	{
		name: 'Pulse Oximeter',
		manufacturer: 'OxyCheck',
		generic_name: 'Pulse oximeter',
		formulation: 'Device',
		strength: 'N/A',
		unit: 'each',
		schedule: 'OTC',
		description: 'Measures oxygen levels and pulse rate!',
		units_per_pack: 1,
		price: 35.0,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 20,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 100,
		expiry_date: new Date('2099-12-31'),
		purchase_date: new Date('2024-05-10'),
		supplierName: 'Pfizer India',
		categoryNames: ['Medical Devices'],
	},
	{
		name: 'Antibacterial Soap',
		manufacturer: 'GermShield',
		generic_name: 'Triclosan',
		formulation: 'Bar',
		strength: 'N/A',
		unit: 'bar',
		schedule: 'OTC',
		description: 'Cleans and protects against germs!',
		units_per_pack: 1,
		price: 3.5,
		tax_rate: 0.05,
		discount: 0.0,
		reorder_level: 200,
		isActive: true,
		isAvailable: true,
		quantity_in_stock: 1500,
		expiry_date: new Date('2027-08-01'),
		purchase_date: new Date('2024-03-01'),
		supplierName: 'Cipla Ltd',
		categoryNames: ['Personal Care'],
	},
]

// Customer data for sales
export const customersData = [
	{ name: 'John Smith', email: 'john.smith@email.com', phone: '9876543210', address: '123 Oak Street, Mumbai' },
	{ name: 'Maria Garcia', email: 'maria.garcia@email.com', phone: '9123456789', address: '456 Pine Avenue, Delhi' },
	{ name: 'David Johnson', email: 'david.johnson@email.com', phone: '9988776655', address: '789 Maple Road, Bangalore' },
	{ name: 'Sarah Wilson', email: 'sarah.wilson@email.com', phone: '9001122334', address: '321 Cedar Lane, Chennai' },
	{ name: 'Walk-in Customer', phone: '0000000000', address: 'Pharmacy Counter' },
]

// Sales data for different time periods (past weeks, months, years)
export const salesData = [
	// Recent sales (past week)
	{
		saleDate: new Date('2025-06-20T10:30:00Z'),
		customerName: 'John Smith',
		paymentMethod: PaymentMethod.CARD,
		items: [
			{ itemName: 'Paracetamol', quantity: 2, discount: 0.05 },
			{ itemName: 'Ibuprofen', quantity: 1, discount: 0.0 },
		],
		overallDiscount: 0.0,
		paymentStatus: 'PAID',
		notes: 'Regular customer purchase'
	},
	{
		saleDate: new Date('2025-06-22T14:15:00Z'),
		customerName: 'Maria Garcia',
		paymentMethod: PaymentMethod.UPI,
		items: [
			{ itemName: 'Amoxicillin', quantity: 1, discount: 0.0 },
			{ itemName: 'Vitamin D3', quantity: 2, discount: 0.1 },
		],
		overallDiscount: 0.02,
		paymentStatus: 'PAID',
		notes: 'Prescription medicines'
	},
	{
		saleDate: new Date('2025-06-24T16:45:00Z'),
		customerName: 'Walk-in Customer',
		paymentMethod: PaymentMethod.CASH,
		items: [
			{ itemName: 'Pediatric Paracetamol', quantity: 3, discount: 0.0 },
		],
		overallDiscount: 0.0,
		paymentStatus: 'PAID',
		notes: 'Walk-in purchase'
	},

	// Past month sales
	{
		saleDate: new Date('2025-05-28T11:20:00Z'),
		customerName: 'David Johnson',
		paymentMethod: PaymentMethod.ONLINE_TRANSFER,
		items: [
			{ itemName: 'Metformin', quantity: 2, discount: 0.0 },
			{ itemName: 'Atorvastatin', quantity: 1, discount: 0.05 },
			{ itemName: 'Omeprazole', quantity: 1, discount: 0.0 },
		],
		overallDiscount: 0.05,
		paymentStatus: 'PAID',
		notes: 'Monthly medication refill'
	},
	{
		saleDate: new Date('2025-05-15T09:30:00Z'),
		customerName: 'Sarah Wilson',
		paymentMethod: PaymentMethod.CARD,
		items: [
			{ itemName: 'Cetirizine', quantity: 2, discount: 0.0 },
			{ itemName: 'Claritin', quantity: 1, discount: 0.0 },
		],
		overallDiscount: 0.0,
		paymentStatus: 'PAID',
		notes: 'Allergy medication'
	},
	{
		saleDate: new Date('2025-05-08T13:45:00Z'),
		customerName: 'John Smith',
		paymentMethod: PaymentMethod.UPI,
		items: [
			{ itemName: 'Insulin Syringes', quantity: 1, discount: 0.0 },
			{ itemName: 'Glucose Test Strips', quantity: 2, discount: 0.15 },
		],
		overallDiscount: 0.0,
		paymentStatus: 'PAID',
		notes: 'Diabetes management supplies'
	},

	// Past few months sales
	{
		saleDate: new Date('2025-03-20T12:00:00Z'),
		customerName: 'Maria Garcia',
		paymentMethod: PaymentMethod.CASH,
		items: [
			{ itemName: 'Lisinopril', quantity: 3, discount: 0.0 },
			{ itemName: 'Calcium Carbonate', quantity: 2, discount: 0.1 },
		],
		overallDiscount: 0.03,
		paymentStatus: 'PAID',
		notes: 'Cardiac medication refill'
	},
	{
		saleDate: new Date('2025-02-14T15:30:00Z'),
		customerName: 'Walk-in Customer',
		paymentMethod: PaymentMethod.CARD,
		items: [
			{ itemName: 'Pediatric Ibuprofen', quantity: 2, discount: 0.0 },
			{ itemName: 'Dextromethorphan Syrup', quantity: 1, discount: 0.0 },
		],
		overallDiscount: 0.0,
		paymentStatus: 'PAID',
		notes: 'Cold and fever treatment'
	},

	// Past year sales
	{
		saleDate: new Date('2024-12-10T10:45:00Z'),
		customerName: 'David Johnson',
		paymentMethod: PaymentMethod.UPI,
		items: [
			{ itemName: 'Atorvastatin', quantity: 2, discount: 0.0 },
			{ itemName: 'Amlodipine', quantity: 2, discount: 0.05 },
			{ itemName: 'Multivitamin Adult', quantity: 1, discount: 0.0 },
		],
		overallDiscount: 0.0,
		paymentStatus: 'PAID',
		notes: 'Cardiac medication refill'
	},
	{
		saleDate: new Date('2024-08-25T14:20:00Z'),
		customerName: 'Sarah Wilson',
		paymentMethod: PaymentMethod.CASH,
		items: [
			{ itemName: 'Ranitidine', quantity: 1, discount: 0.0 },
			{ itemName: 'Antacid Chewables', quantity: 1, discount: 0.0 },
			{ itemName: 'Probiotic Blend', quantity: 2, discount: 0.1 },
		],
		overallDiscount: 0.05,
		paymentStatus: 'PAID',
		notes: 'Digestive health medication'
	},
]
